-- SOLATIA FINANCE DATABASE SCHEMA

-- 1. Configuration Table (What we track)
CREATE TABLE tracked_assets (
    ticker TEXT PRIMARY KEY,
    search_term TEXT NOT NULL,
    sentiment_threshold NUMERIC DEFAULT 0.2, -- AI Sensitivity
    anomaly_threshold NUMERIC DEFAULT 3.0,   -- Volume Z-Score Trigger
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Market Data (1-Minute Candles)
-- Optimized for time-series charts
CREATE TABLE market_candles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker TEXT REFERENCES tracked_assets(ticker) ON DELETE CASCADE,
    open NUMERIC,
    high NUMERIC,
    low NUMERIC,
    close NUMERIC,
    volume NUMERIC,
    time TIMESTAMPTZ NOT NULL
);

-- Index for instant chart loading
CREATE INDEX idx_candles_ticker_time ON market_candles(ticker, time DESC);

-- 3. Solatia Intelligence Log (Alerts)
CREATE TABLE signals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker TEXT REFERENCES tracked_assets(ticker) ON DELETE CASCADE,
    type TEXT CHECK (type IN ('ANOMALY', 'SENTIMENT')),
    message TEXT,
    sentiment_score NUMERIC, -- -1.0 to 1.0
    rvol NUMERIC,            -- Relative Volume Ratio
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Initial Seed Data
INSERT INTO tracked_assets (ticker, search_term) VALUES 
('AAPL', 'Apple stock'),
('TSLA', 'Tesla stock'),
('NVDA', 'Nvidia AI'),
('SPY', 'SPY ETF market');